version: '3'

services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  web:
    build: .
    ports:
    - "8080:8080"
    links:
    - db


